// content information
// weapon stats
const weapon = new Map([
    // ["Weapon",    ["name","cost","range","damage","shots","wound","special","img"]],
    ["Boarding Axe",    [null,"150cr","Adjacent","2d10 DMG","N/A","Gore [+]","","boardingaxe"]],
    ["Combat Shotgun",  ["KANO X9","1.4krc","Close","4d10 DMG","4","Gunshot","1d10 DMG at Long Range or greater.","shotgun"]],
    ["Crowbar",         [null,"25cr","Adjacent","1d5 DMG","N/A","Blunt Force [+]","Grants [+] on Strength Checks to open jammed airlocks, lift heavy objects, etc.","crowbar1"]],
    ["Flamethrower",    ["RAMHORN 1","4kcr","Close","2d10 DMG","4","Fire/Explosives[+]","Body Save [-] or be set on fire (2d10DMG / round).","flame"]],
    ["Flare Gun",       ["PEABODY","25cr","Long","1d5 DMG","4","Fire/Explosives[-]","High intensity flare visible day and night from Long Range.","flare"]],
    ["Foam Gun",        ["HALLS B SERIES","500cr","Close","1 DMG","3","Blunt Force","Body Save or become stuck. Strength Check [-] to escape.","foam"]],
    ["Frag Grenade",    [null,"400cr ea.","Close","3d10 DMG","1","Fire/Explosives","On a hit, damages all Adjacent to enemy.","frag"]],
    ["General-Purpose Machine Gun", [null,"4.5kcr","Long","4d10 DMG","5","Gunshot [+]","Two-handed. Heavy. Barrel can be maneuvered to fire around corners.","gpmg"]],
    ["Hand Welder",     ["EVA MK II","250cr","Adjacent","1d10 DMG","N/A","Bleeding","Can cut through airlock doors.","welder"]],
    ["Laser Cutter",    ["MNC MODE A","1.2kcr","Long","1d100 DMG","6","Bleeding [+] or Gore [+]","Two-handed. Heavy. 1 round recharge between shots.","laser"]],
    ["Nail Gun",        ["ROSCO SS6","150cr","Close","1d5 DMG","32","Bleeding",null,"nailgun"]],
    ["Pulse Rifle",     ["F20 “ARBITER”","2.4kcr","Long","3d10 DMG","5","Gunshot",null,"pulserifle"]],
    ["Revolver",        ["FN SLUG","750cr","Close","1d10+1 DMG","6","Gunshot",null,"revolver"]],
    ["Rigging Gun",     ["HAN-290","350cr","Close","1d10 DMG + 2d10 DMG when removed","1","Bleeding [+]","100m micro-filament. Body Save or become entangled.","rigging"]],
    ["Scalpel",         [null,"50cr","Adjacent","1d5 DMG","N/A","Bleeding [+]",null,"scalpel"]],
    ["Smart Rifle",     ["SK 109 SEEKER","5kcr","Extreme","4d10 DMG (AA)","3","Gunshot [+]","[-] on Combat Check when fired at Close Range.","smartrifle"]],
    ["SMG",             ["ARMA 29","1kcr","Long","2d10 DMG","5","Gunshot","Can be fired one-handed.","smg"]],
    ["Stun Baton",      [null,"150cr","Adjacent","1d5 DMG","N/A","Blunt Force","Body Save or stunned 1 round.","stunbaton"]],
    ["Tranq Pistol",    ["D&C 7","250cr","Close","1d5 DMG","6","Blunt Force","If DMG dealt: enemy must Body Save or be unconscious 1d10 rounds.","tranq"]],
    ["Vibechete",       [null,"1kcr","Adjacent","3d10 DMG (AA)","N/A","Bleeding + Gore","When dealing a Wound, roll on BOTH the Bleeding AND Gore columns.","vibechete"]],
    ["EMP Javelin*",    [null,"cost","Close","1d10 DMG","1","Bleeding","Disables electronics while embedded.","missing"]],

]);

// armor stats
const armor = new Map([
    // ["armor",    ["name","cost","AP","O2","SPEED",null,"SPECIAL","img"]],
    ["Standard Crew Attire",    ["Basic clothing.","100cr","1","None","Normal",null,null,"stdcrew"]],
    ["Vaccsuit",                ["Designed for outer space operations.","10kcr","3","12 hrs","[-]",null,"Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.","vacsuit"]],
    ["Hazard Suit",             ["Environmental protection while exploring unknown planets.","4kcr","5","1 hrs","Normal",null,"Includes air filter, extreme heat/cold protection, hydration reclamation (1L of water lasts 4 days), short-range comms, headlamp, and radiation shielding.","hazardssuit"]],
    ["Standard Battle Dress",   ["Lightly-plated armor worn by most marines.","2kcr","7","None","Normal",null,"Includes short-range comms.","stdbattle"]],
    ["Advanced Battle Dress",   ["Heavy armor for marines deployed in high combat offworld engagements.","12kcr","10","1 hr","[-]",null,"Includes short-range comms, body cam, headlamp, HUD, exoskeletal weave (Strength Checks [+]), and radiation shielding. Damage Reduction: 3.","advanced battle dress1"]],
    ["Standard Armor Vest*",    ["Light armor worn by law-enforcement.","1kcr","4","None","Normal",null,null,"missing"]],
]);

// item stats
const item = new Map([
    // ["item",    ["name","cost",null,null,null,null,"description","img"]],
    ["Assorted Tools",      [null,"20cr",null,null,null,null,"Wrenches, spanners, screwdrivers, etc. Can be used as weapons in a pinch (1d5 DMG).","tools"]],
    ["Automed (x5)",        [null,"1.5kcr",null,null,null,null,"Nanotech pills that assist your body in repairing Damage by granting Advantage to Body Saves meant to repel disease and poison, as well as attempts to heal from rest.","automed"]],
    ["Battery (High Power)",[null,"500cr",null,null,null,null,"Heavy duty battery used for powering laser cutters, salvage drones, and other items. Can be recharged in 1 hour if connected to power or in 6 hours with solar power. Add waterproofing (+500cr).","missing"]],
    ["Binoculars",          [null,"150cr",null,null,null,null,"20x magnification. Add night vision (+300cr) or thermal vision (+1kcr).","binoculars1"]],
    ["Bioscanner",          [null,"3kcr",null,null,null,null,"Long Range. Allows the user to scan for signs of life. Can tell the location of signs of life, but not what that life is. Blocked by some materials at the Warden's discretion.","bioscan"]],
    ["Body Cam",            [null,"50cr",null,null,null,null,"A camera worn on your clothing that can stream video back to a control center so your other crewmembers cansee what you're seeing. Add night vision (+300cr) or thermal vision (+1kcr).","bodycam"]],
    ["Chemlight (x5)",      [null,"5cr",null,null,null,null,"Small disposable glowsticks capable of dim illumination in a 1m radius.","missing"]],
    ["Crowbar",             [null,"25cr",null,null,null,null,"Grants Advantage on Strength Checks to open jammed airlocks, lift heavy objects, etc. Cybernetic Diagnostic","crowbar1"]],
    ["Scanner",             [null,"2kcr",null,null,null,null,"Allows the user to scan androids and other cybernetic organisms in order to diagnose any physical or mental issues they may be having. Often distrusted by androids.","scanner"]],
    ["Electronic Tool Set", [null,"100cr",null,null,null,null,"A full set of tools for doing detailed repair or construction work on electronics.","tools"]],
    ["Emergency Beacon",    [null,"2kcr",null,null,null,null,"A small device that sends up a flare and then emits a loud beep every few seconds. Additionally, sends out a call on all radio channels to ships or vehicles in the area, but can be blocked by a radio jammer.","missing"]],
    ["Exoloader",           [null,"100kcr",null,null,null,null,"Open-air mechanical exoskeleton used for heavy lifting (up to 5000kg). Loader claws deal 1 Wound. User can only wear Standard Crew Attire or Standard Battle Dress while operating. Battery operated (48 hours of use).","missing"]],
    ["Explosives & Detonator",    [null,"500cr",null,null,null,null,"Explosive charge powerful enough to blow open an airlock. All organisms in Close Range must make a Body Save or take a Wound (Explosive). Detonator works at Long Range, but can be blocked by a radio jammer.","explosive"]],
    ["First Aid Kit",       [null,"75cr",null,null,null,null,"An assortment of dressings and treatments to help stop bleeding, bandage cuts, and treat other minor injuries.","firstaid"]],
    ["Flashlight",          [null,"30cr",null,null,null,null,"Handheld or shoulder mounted. Illuminates 10m ahead of the user.","torch"]],
    ["Foldable Stretcher",  [null,"150cr",null,null,null,null,"Portable stretcher that can fit within a rucksack. Allows the user to safely strap down the patient and carry them to a location where their wounds can be better treated. Unfolds to roughly 2m.","missing"]],
    ["Geiger Counter",      [null,"20cr",null,null,null,null,"Detects radiation and displays radiation levels.","geiger"]],
    ["Heads-Up Display (HUD)",    [null,"100cr",null,null,null,null,"Often worn by marines, the HUD allows the wearer to see through the body cams of others in their unit, and connect to any smart-link upgraded weapon.","hud"]],
    ["Infrared Goggles",    [null,"1.5kcr",null,null,null,null,"Allows the wearer to see heat signatures, sometimes up to several hours old. Add night vision (+300cr).","goggles"]],
    ["Jetpack",             [null,"75kcr",null,null,null,null,"Allows wearer to fly up to 100m high and up to a speed of 100km/hr for 2 hours on a tank of fuel. Deals 1d100[+] DMG if destroyed. Fuel can be refilled for 200cr.","missing"]],
    ["Lockpick Set",        [null,"40cr",null,null,null,null,"A highly advanced set of tools meant for hacking basic airlock and electronic door systems.","lockpick"]],
    ["Long-range Comms",    [null,"1kcr",null,null,null,null,"Rucksack-sized communication device for use in surface-to-ship communication.","commslong"]],
    ["Mag-boots",           [null,"350cr",null,null,null,null,"Grants a magnetic grip to the wearer, allowing them to easily walk on the exterior of a ship (in space, while docked, or free-floating), metal-based asteroids, or any other magnetic surface.","magboots"]],
    ["Medscanner",          [null,"8kcr",null,null,null,null,"Allows the user to scan a living or dead body to analyze it for disease or abnormalities, without having to do a biopsy or autopsy. Results may not be instantaneous and may require a lab for complete analysis.","medscanner"]],
    ["MoHab Unit",          [null,"1kcr",null,null,null,null,"Tent, canteen, stove, rucksack, compass, and sleeping bag.","mohab"]],
    ["MRE (x7)",            [null,"70cr",null,null,null,null,"“Meal, Ready-to-Eat.” Self-contained, individual field rations in lightweight packaging. Each has sufficient sustenance for a single person for one day (does not include water).","mre"]],
    ["Mylar Blanket",       [null,"10cr",null,null,null,null,"Lightweight blanket made of heat-reflective material. Often used for thermal regulation of patients suffering from extreme cold or other trauma.","missing"]],
    ["Oxygen Tank",         [null,"50cr",null,null,null,null,"When attached to a vaccsuit provides up to 12 hours of oxygen under normal circumstances, 4 hours under stressful circumstances. Explosive.","o2"]],
    ["Paracord (50m)",      [null,"10cr",null,null,null,null,"General purpose lightweight nylon rope.","missing"]],
    ["Patch Kit (x3)",      [null,"200cr",null,null,null,null,"Repairs punctured and torn vaccsuits, restoring their space readiness. Patched vaccsuits have an AP of 1.","missing"]],
    ["Personal Locator",    [null,"200cr",null,null,null,null,"Allows crewmembers at a control center (or on the bridge of a ship) to track the location of the wearer.","locator"]],
    ["Pet (Organic)",       [null,"200kcr",null,null,null,null,"Small to medium-sized organic pet animal. Larger or rare pets cost 2d10x base pet cost.","missing"]],
    ["Pet (Synthetic)",     [null,"15kcr",null,null,null,null,"Small to medium-sized synthetic pet animal. Larger or rare pets cost 2d10x base pet cost.","missing"]],
    ["Portable Computer Terminal",  [null,"1.5kcr",null,null,null,null,"Flat computer monitor, keyboard and interface which allows the user to hack into pre-existing computers and networks, as well as perform standard computer tasks.","missing"]],
    ["Radiation Pills (x5)",    [null,"200cr",null,null,null,null,"Take 1d5 DMG and reduce your Radiation Level (see pg. 33.2) by 1 for 2d10 minutes.","pills"]],
    ["Radio Jammer",        [null,"4kcr",null,null,null,null,"Rucksack-sized device which, when activated, renders all radio signals within 100km incomprehensible.","radiojammer"]],
    ["Rebreather",          [null,"500cr",null,null,null,null,"When worn, filters toxic air and/or allows for underwater breathing for up to 20 minutes at a time without resurfacing. Can be connected to an oxygen tank.","rebreather"]],
    ["Rucksack",            [null,"50cr",null,null,null,null,"Large, durable, waterproof backpack.","missing"]],
    ["Salvage Drone",       [null,"10kcr",null,null,null,null,"Battery operated remote controlled drone. Requires two hands to operate receiver. Can fly up to 450m high, to a distance of 3km from operator. Can run for 2 hours. Can record and transmit footage to receiver. If purchased separately, can be equipped with up to two of the following: binoculars, radio jammer, Geiger counter, laser cutter, medscanner, personal locator, infrared goggles, emergency beacon, cybernetic diagnostic scanner, bioscanner. Can carry up to 20-30kg.","missing"]],
    ["Sample Collection Kit",   [null,"50cr",null,null,null,null,"Used to research xenoflora and xenofauna in the field. Can take vital signs, DNA samples ,and collect other data on foreign material. Results may not be instantaneous and may require a lab for complete analysis.","samplekit"]],
    ["Short-range Comms",   [null,"100cr",null,null,null,null,"Allows communication from ship-to-ship within a reasonable distance, as well as surface-to-surface within a dozen kilometers. Blocked by radio jammer.","commsshort"]],
    ["Smart-link Add-On",   [null,"10kcr",null,null,null,null,"Grants remote viewing, recording, and operation of a ranged weapon as well as +5 DMG to the weapon.","missing"]],
    ["Stimpak",             [null,"1kcr",null,null,null,null,"Cures cryosickness, reduces Stress by 1, restores 1d10 Health, and grants [+] to all rolls for 1d10 min. Roll 1d10. If you roll under the amount of doses you've taken in the past 24 hours, make a Death Save.","stimpak"]],
    ["Water Filtration Device", [null,"50cr",null,null,null,null,"Can pump 4 liters of filtered water per hour from even the most brackish swamps.","waterfilter"]],
    ["Nano tape (double sided)*",    ["name","cost",null,null,null,null,"Synthetic adhesive polymer tape consisting of arrays of carbon nanotubes.","missing"]],
    ["Micro-filament wire*",    ["name","cost",null,null,null,null,"Thin and durable wire.","missing"]],    
]);

// Cyberware stats
const cyberware = new Map([
    // ["cyberware", ["cyberware","cost","slots",null,null,"requires","description",null]],
    ["Big Switch",  [null,"18kcr","1",null,null,null,"Allows the user to change their primary sexual characteristics. Takes 1 hour and a mental trigger.","missing"]],
    ["Black Box",   [null,"200kcr","1",null,null,"Slicksocket","Eidetic memory backup. Memories can be watched with an OGRE or projected with a Holoprojector. Only saves complete memories from the time of installation onward. Also stores any uploaded data or slickware.","missing"]],
    ["Cloakskin",   [null,"200kcr","1",null,null,null,"Near-invisibility for 5 minutes once per day. If a Wound is gained during use there is a 30% chance condition is permanent.","missing"]],
    ["Deadswitch",  [null,"5kcr","1",null,null,"Black Box","Feigns death for 2 weeks. Every time the switch is used there's a cumulative 5% chance the condition is permanent.","missing"]],
    ["Fangs",       [null,"2kcr","0",null,null,null,"Hollow cybernetic fangs. 2d10 DMG. Can store up to 3 doses of poison, medicine or any other drug.","missing"]],
    ["Handcannon",  [null,"6kcr+ Weapon","Varies*",null,null,null,"Conceals a weapon inside a prosthetic limb. Slots and cost are based on the weapon used.","missing"]],
    ["Holoprojector", [null,"750cr","1",null,null,"OGRE","Holographically project stored data (collected via OGRE, Installed Body Cam, Black Box, Slicksocket, etc.).","missing"]],
    ["Hotswap",     [null,"5kcr","0",null,null,null,"Allows a 1 turn changing of cyberware.","missing"]],
    ["Huntershot", [null,"4.5kcr","1",null,null,"OGRE","Holds 1 dart which can be fired on command, upon death or unconsciousness. 2d10 DMG.","missing"]],
    ["Little Switch", [null,"8kcr","0",null,null,null,"Allows the user to smooth or roughen their appearance. Takes 1 day and a mental trigger.","missing"]],
    ["Loudmouth", [null,"500cr","0",null,null,null,"Allows for recording and playback of audio. Maximum volume equivalent to that of a flashbang.","missing"]],
    ["Lumatat", [null,"200cr+","0",null,null,null,"Cosmetic, color changing, animated or luminescent tattoos.","missing"]],
    ["OGRE", [null,"24kcr","1",null,null,null,"Occular Graphic Rendering Engine. A Heads-Up Display implanted into the optical nerve which projects directly into user's field of vision.","missing"]],
    ["Panic Button", [null,"10kcr","1",null,null,null,"When triggered (on purpose or upon death) violently detonates hidden explosives. Everyone within Close Range must make a Body Save or take 3d10 DMG. If knocked unconscious there is a 5% chance this will trigger automatically.","missing"]],
    ["Panzersfist", [null,"5mcr","3",null,null,"Prosthetic","A miniaturized missile launcher hidden inside a prosthetic. Extreme Range, 2d10x10 DMG. Shots: 2. Wound: Fire/Explosion [+]. Reloading takes a round. Without a Spinal Rig user must make a Body Save or be flung backwards. Takes 2 rounds to fire.","missing"]],
    ["Prosthetic", [null,"2kcr","0",null,null,null,"Artificial hand, foot, arm or leg. Prosthetic organs can also replace any damaged organs, though at 10x the cost.","missing"]],
    ["Remote Uplink", [null,"2mcr","1",null,null,"Black Box","Once per day sends a PDCP encrypted broadcast of user's Black Box data to a secure backup site for future retrieval or reloading. Many services require authorized next-of-kin.","missing"]],
    ["Retractable Nanoblade", [null,"80kcr","1",null,null,null,"Retractable 9\" blade which can cut through almost anything. 2d10 DMG.","missing"]],
    ["Revenant Protocol", [null,"20kcr","1",null,null,null,"If triggered within 2 rounds of death, allows the user to continue fighting for 2d10 rounds after death. If there are no remaining enemies, user must roll randomly for targets.","missing"]],
    ["Scapegoat System", [null,"10kcr","1",null,null,null,"For every 10 DMG user takes, Scapegoat System gains 1 Charge. Charges can be released via touch for 2d10 DMG. Holds 3 charges.","missing"]],
    ["Slicksocket", [null,"500cr","1",null,null,null,"Cranial input jack which allows slickware to be installed.","missing"]],
    ["Sockpuppet", [null,"1mcr+ Weapon","1",null,null,"Spinal Rig","Allows the user to install a weapon which can fire on its own once per round using the user's Combat Stat.","missing"]],
    ["Spider Mount", [null,"250kcr","0",null,null,"Spinal Rig","Grants +1 slot. Can only be installed once.","missing"]],
    ["Spinal Rig", [null,"150kcr","1",null,null,null,"Mechanical rig built for assisted heavy-lifting. User gains 10 Strength (and 1 slot). Can only be installed once.","missing"]],
    ["Subdermal Armor", [null,"5mcr","1",null,null,null,"Grants user a layer of rechargeable armor (5 AP) beneath their skin. Takes 2 weeks to regrow if used.","missing"]],
    ["Tattletale", [null,"2kcr","0",null,null,null,"Detachable audio surveillance bug which can be traced up to 100km to within a 100m area.","missing"]],
    ["Terminal Jack", [null,"750cr","1",null,null,null,"Port allowing interface with terminals, smartlink weapons, and vehicles. Can download data from linked systems or upload information from a Black Box.","missing"]],
    ["Whiplash Injector", [null,"4mcr","1",null,null,null,"Single use. Automatically restores 1 Wound upon user's death. Reduces Body Save by 1d10 [-] after use.","missing"]]
]);